import type { Metadata } from "next";
import "./globals.css";
import Headbar from "./components/Headbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div>
          <Headbar />
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
